version: '3.1'

services:

  psql:
    container_name: psql
    image: postgres:13.1-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: docstore
    ports:
      - "5432:5432"

  docstore:
    container_name: docstore
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - psql
    command: python manage.py runserver 0.0.0.0:8000